apiVersion: v1
kind: Service
metadata:
  name: ssl-app-service
  labels:
    app: ssl-app
spec:
  type: LoadBalancer
  selector:
    app: ssl-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000